version: '3.8'

services:

  db:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: ""
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db:3306/mydatabase?allowPublicKeyRetrieval=true&useSSL=false -user=user -password=userpassword migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - db

volumes:
  mysql-data:
